### PR TITLE
Added 'response_type' setting

### PR DESCRIPTION
**Pull request by sparkwatson**
Slack's 'response_type' setting ('ephemeral' | 'in_channel') 
determines the visibility of responses in a channel.

if 'ephemeral', then the bot response is invisible to other members in a channel
if 'in_channel',  then the bot response is *visible* to other members in a channel

see 'message visibility' under: https://api.slack.com/interactivity/slash-commands#sending_an_immediate_response

### CODE REVIEW

**Comment by alek13** [comment]
@sparkwatson , thanx for PR.
Please, fix testst https://travis-ci.org/php-slack/slack/jobs/650445998?utm_medium=notification&utm_source=github_status

**Comment by sparkwatson** [comment]
@alek13 thanks - I fixed the Travis tests... I'm unsure on the styleci one (indentation issue)... I didn't change the indentation.

**Comment by alek13** [comment]
@sparkwatson thnx.
Style CI I fix already in master

**Comment by sparkwatson** [comment]
Great, thank you @alek13 !

**Pull request merged**
