### PR TITLE
Added callback_id to Attachment.php

### PR DESCRIPTION
**Pull request by GRMrGecko**
Added callback_id to Attachment.php to allow for working with the interactivity callback api in slack. Without this, Slack will not call back to your API web hook.

### CODE REVIEW

**Comment by alek13** [comment]
@GRMrGecko Thank you for PR. Can you fix tests ?

**Comment by GRMrGecko** [comment]
Hello,

Unit tests were adjusted to add the callback id.

**Comment by alek13** [comment]
Hi @GRMrGecko , you can find out what went wrong under https://scrutinizer-ci.com/g/php-slack/slack/inspections/8b359ae4-808d-4e00-b94e-e2a0ff80955b
or just run tests locally on your machine.

**Comment by GRMrGecko** [comment]
@alek13 Thank you for being patient with me, I'm fairly new to doing unit tests with PHP and when I viewed the test failed page, I went over to the issues tab and all issues page. Did not understand the issue was on the first page.

**Pull request merged**
