### PR TITLE
Update Composer and PHPUnit to PHP 8.0

### PR DESCRIPTION
**Pull request by phpfui**
PHP 8.0 shipped today, and Composer and PHPUnit prevents this package from upgrading to PHP 8.0

 * Updated the unit tests to be compatible with PHPUnit 9.4
 * Added PHP 7.4 and 8.0 to Travis CI, but PHP 8.0 is not yet supported
 * Updated composer.json to be compatible with PHP 8.0
 * Confirmed unit tests work with PHP 7.1 and higher

### CODE REVIEW

**Comment by alek13** [comment]
wait for 8.0 in travis: https://travis-ci.community/t/php-8-0-missing/10132/15

**Comment by phpfui** [comment]
Looks like Travis is now supporting PHP 8.0.  Kick off the build again, should pass now.

**Comment by alek13** [comment]
Yep! It remains to understand why Scrutinizer fails.

**Comment by phpfui** [comment]
I don't use Scrutinizer, but there is this error from PHPUnit: Error: Incorrect whitelist config, no code coverage will be generated.

I don't see that when I run tests locally.

**Comment by phpfui** [comment]
Also this: The coverage file '/home/scrutinizer/build/some-file' was not found.

**Comment by alek13** [comment]
I think he tries to get file with coverage info, but it missing.
I think its because you deleted `<whitelist>` section

**Comment by phpfui** [comment]
I think that had a problem with some versions of PHPUnit.  Will check again tonight.

**Comment by phpfui** [comment]
I was able to get a good PHP 8.0 build just now on my account.  See if you can restart just that job.  Looks like Scrutinizer is happy now.

**Comment by phpfui** [comment]
Hmm, maybe not.  Another package of mine is not passing PHP 8.0 on travis.  Not sure what is going on with them, sometimes it works, but mostly not!

**Comment by phpfui** [comment]
Good stuff!!! Thank you.

**Pull request merged**
