### PR TITLE
Add "header" as a valid block type

### PR DESCRIPTION
**Pull request by KennedyTedesco**
Reference: https://api.slack.com/reference/block-kit/blocks#header

### CODE REVIEW

**Comment by cmbuckley** [comment]
Hi @KennedyTedesco - this line alone won't be enough to create a Header block. The corresponding class would also need to be created - see the other blocks in [src/Blocks](https://github.com/php-slack/slack/tree/master/src/Block) (and the corresponding [unit tests](https://github.com/php-slack/slack/tree/master/tests/Block)).

**Comment by KennedyTedesco** [comment]
My bad! I've got an exception when I was trying to build blocks manually. I completely forgot about those classes because I'm not using them.

 If I have time, I'll be back with the complete implementation. 

Cheers!

**Comment by alek13** [comment]
@KennedyTedesco released in [2.1.0](https://github.com/php-slack/slack/releases/tag/2.1.0)
Thanks to @cmbuckley

**Comment by KennedyTedesco** [comment]
That's awesome! \o/ ❤️

**Pull request closed without merging**
